# Локальные секреты (не коммитить в GitHub!)
POSTGRES_HOST = "localhost"
POSTGRES_DB = "review_analysis"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "123456"

MONGO_URI = "mongodb+srv://admin:qwerty123@cluster0.4jhoran.mongodb.net/."